version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "15:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/react-native"
    versions:
    - "> 0.62.18"
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: metro-react-native-babel-preset
    versions:
    - 0.64.0
    - 0.65.0
    - 0.65.1
    - 0.65.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
- package-ecosystem: npm
  directory: "/example"
  schedule:
    interval: weekly
    time: "15:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-dom
    versions:
    - "> 16.11.0"
  - dependency-name: react-native-web
    versions:
    - "> 0.11.7"
  - dependency-name: "@types/react-native"
    versions:
    - "> 0.62.18"
  - dependency-name: "@expo/webpack-config"
    versions:
    - 0.12.53
    - 0.12.57
    - 0.12.58
    - 0.12.59
    - 0.12.60
    - 0.12.61
    - 0.12.63
    - 0.12.64
    - 0.12.65
    - 0.12.66
  - dependency-name: expo
    versions:
    - 40.0.1
    - 41.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: expo-font
    versions:
    - 9.0.0
